## problem 1

In [2]:
import numpy as np
import random

In [2]:
np.random.seed(42)
random.seed(42)

In [3]:
a = np.random.randint(1,51 ,size=(5, 4))
print(a)

[[39 29 15 43]
 [ 8 21 39 19]
 [23 11 11 24]
 [36 40 24  3]
 [22  2 24 44]]


#### printing anti-diagonal elements

In [8]:
anti_dia = []
for i in range(5):
   col = 3 -i
   if col >= 0:
      anti_dia.append(a[i, col])

print(f"anti-diagonal elements: {anti_dia}")
                   

anti-diagonal elements: [43, 39, 11, 36]


#### finding max in each row

In [9]:
row_max = []
for i in range(5):
    max_in_row = max(a[i])
    row_max.append(max_in_row)

print(f"maximum values: {row_max}")

maximum values: [43, 39, 24, 40, 44]


#### finding elements less than or equal to overall average

In [10]:
all_nums = a.flatten() # making 2d array into 1d
overall_mean = sum(all_nums) / len(all_nums)
print(f"overall average: {overall_mean:.2f}")

overall average: 23.85


In [11]:
ele_below_mean = []
for num in all_nums:
    if num <= overall_mean:
        ele_below_mean.append(num)

print(f" elements <= avg : {ele_below_mean}")

 elements <= avg : [15, 8, 21, 19, 23, 11, 11, 3, 22, 2]


#### function numpy_boundary_traversal(matrix)

In [23]:
def numpy_boundary_traversal(matrix):
    rows, cols = matrix.shape
    result = []
    for j in range(cols): # L -> R (across the top row)
        result.append(matrix[0, j])
        print(f"added: {matrix[0, j]}") 
        
    for i in range(1, rows): # down the right side, skipping top corner
        result.append(matrix[i, cols-1])
        print(f"added: {matrix[i, cols-1]}")
        
    if rows>1: # accross bottom row (R -> L), only if we have more than 1 row
        for j in range(cols-2, -1, -1):
            result.append(matrix[rows-1, j])
            print(f"added: {matrix[rows-1, j]}")
            
    if cols>1: # left side, skipping corners, only if we have more than 1 column
        for i in range(rows-2, 0, -1):
            result.append(matrix[i, 0])
            print(f"added: {matrix[i,0]}")
            
    return result

In [24]:
print("tracing boundary of array:")
boundary_elements = numpy_boundary_traversal(a)
print(f"boundary path: {boundary_elements}")

tracing boundary of array:
added: 39
added: 29
added: 15
added: 43
added: 19
added: 24
added: 3
added: 44
added: 24
added: 2
added: 22
added: 36
added: 23
added: 8
boundary path: [39, 29, 15, 43, 19, 24, 3, 44, 24, 2, 22, 36, 23, 8]


## problem 2

In [25]:
b = np.random.uniform(0, 10, size=20)
print(b)

[9.38552709e+00 7.78765841e-03 9.92211559e+00 6.17481510e+00
 6.11653160e+00 7.06630522e-02 2.30624250e-01 5.24774660e+00
 3.99860972e+00 4.66656632e-01 9.73755519e+00 2.32771340e+00
 9.06064345e-01 6.18386009e+00 3.82461991e+00 9.83230886e+00
 4.66762893e+00 8.59940407e+00 6.80307539e+00 4.50499252e+00]


#### round all to 2 decimal places

In [28]:
rounded_b = np.round(b, 2)
print(rounded_b)

[9.39 0.01 9.92 6.17 6.12 0.07 0.23 5.25 4.   0.47 9.74 2.33 0.91 6.18
 3.82 9.83 4.67 8.6  6.8  4.5 ]


#### find min, max, and median

In [29]:
min_val = min(rounded_b)
max_val = max(rounded_b)
sorted_b = sorted(rounded_b)
median_val = sorted_b[len(sorted_b)//2]

In [30]:
print(f"minimum: {min_val}")
print(f"maximum: {max_val}")
print(f"median: {median_val}")

minimum: 0.01
maximum: 9.92
median: 5.25


#### replace nums less than 5 with their squares

In [36]:
modified_arr = rounded_b.copy()

In [37]:
for i in range(len(modified_arr)):
    if modified_arr[i] < 5:
        old_val = modified_arr[i]
        modified_arr[i] = old_val ** 2

print(f"modified array: {modified_arr}")     

modified array: [9.39000e+00 1.00000e-04 9.92000e+00 6.17000e+00 6.12000e+00 4.90000e-03
 5.29000e-02 5.25000e+00 1.60000e+01 2.20900e-01 9.74000e+00 5.42890e+00
 8.28100e-01 6.18000e+00 1.45924e+01 9.83000e+00 2.18089e+01 8.60000e+00
 6.80000e+00 2.02500e+01]


####  function numpy_alternate_sort(array)

In [38]:
def numpy_alternate_sort(array):
    sorted_arr = sorted(array)
    result = []
    
    left = 0 # points to smallest remaining
    right = len(sorted_arr) - 1 # points to largest remaining 
    
    while left <= right:
        if len(result) % 2==0: # even positions get small nos
            print(f"position {len(result)-1}: added smallest remaining = {sorted_arr[left]}")
            left += 1
        else: # odd ones get large nos
            result.append(sorted_arr[right])
            print(f"Position {len(result)-1}: Added largest remaining = {sorted_arr[right]}")
            right -= 1
            
    return np.array(result)

In [42]:
alt_sorted = numpy_alternate_sort(rounded_b)
print(f" alternating sorted result: {alt_sorted}")

position -1: added smallest remaining = 0.01
position -1: added smallest remaining = 0.07
position -1: added smallest remaining = 0.23
position -1: added smallest remaining = 0.47
position -1: added smallest remaining = 0.91
position -1: added smallest remaining = 2.33
position -1: added smallest remaining = 3.82
position -1: added smallest remaining = 4.0
position -1: added smallest remaining = 4.5
position -1: added smallest remaining = 4.67
position -1: added smallest remaining = 5.25
position -1: added smallest remaining = 6.12
position -1: added smallest remaining = 6.17
position -1: added smallest remaining = 6.18
position -1: added smallest remaining = 6.8
position -1: added smallest remaining = 8.6
position -1: added smallest remaining = 9.39
position -1: added smallest remaining = 9.74
position -1: added smallest remaining = 9.83
position -1: added smallest remaining = 9.92
 alternating sorted result: []


In [43]:
## redo the above one

## problem 3

In [3]:
import pandas as pd

#### creating student data

In [46]:
names = ['anya', 'loid', 'yor', 'damian', 'yuki', 'frankie', 'sylvia', 'fiona', 'becky', 'henry']
subjects = ['maths', 'science', 'english', 'social science', 'german']

In [47]:
students_data = []
for name in names:
    subject = random.choice(subjects)
    score = random.randint(50, 100)
    students_data.append({
    'name': name,
    'subject': subject,
    'score': score,
    'grade': ''
    })

In [48]:
df_students = pd.DataFrame(students_data)
print("student records:")
print(df_students)

student records:
      name  subject  score grade
0     anya    maths     51      
1     loid  english     65      
2      yor  science     58      
3   damian    maths     93      
4     yuki   german     55      
5  frankie   german     77      
6   sylvia    maths     51      
7    fiona    maths     63      
8    becky  science     82      
9    henry   german     51      


#### assigning grades based on scores

In [49]:
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

In [51]:
for i in range(len(df_students)):
    score = df_students.iloc[i]['score']
    grade = assign_grade(score)
    df_students.iloc[i, df_students.columns.get_loc('grade')] = grade
    print(f"{df_students.iloc[i]['name']}: {score} -> {grade}")

anya: 51 -> F
loid: 65 -> D
yor: 58 -> F
damian: 93 -> A
yuki: 55 -> F
frankie: 77 -> C
sylvia: 51 -> F
fiona: 63 -> D
becky: 82 -> B
henry: 51 -> F


#### sort by score 

In [52]:
print("sorting by score (highest first):")
df_sorted = df_students.sort_values('score', ascending=False)
print(df_sorted)

sorting by score (highest first):
      name  subject  score grade
3   damian    maths     93     A
8    becky  science     82     B
5  frankie   german     77     C
1     loid  english     65     D
7    fiona    maths     63     D
2      yor  science     58     F
4     yuki   german     55     F
0     anya    maths     51     F
6   sylvia    maths     51     F
9    henry   german     51     F


#### average score for each subject

In [55]:
subjects_average = {}
for subject in subjects:
    subject_data = df_students[df_students['subject'] == subject]
    if len(subject_data) >0:
        avg_score = subject_data['score'].mean()
        subjects_average[subject] = avg_score
        print(f"{subject}: {avg_score:.1f}")

maths: 64.5
science: 70.0
english: 65.0
german: 61.0


#### function pandas_filter_pass(dataframe)

In [56]:
def pandas_filter_pass(dataframe):
    
    passed_students = dataframe[dataframe['grade'].isin(['A', 'B'])]
    return passed_students

In [57]:
passed_students = pandas_filter_pass(df_students)
print("students with A or B grades:")
print(passed_students)

students with A or B grades:
     name  subject  score grade
3  damian    maths     93     A
8   becky  science     82     B


## problem 4

In [1]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [4]:
# simple movie reviews:

In [5]:
positive_reviews = ["great movie loved it", "amazing film wonderful", "excellent story fantastic",
    "brilliant acting superb", "perfect movie amazing", "outstanding film great",
    "wonderful story excellent", "fantastic acting brilliant", "incredible movie perfect",
    "superb film outstanding", "amazing story wonderful", "excellent movie fantastic",
    "great acting brilliant", "perfect film incredible", "wonderful movie superb",
    "outstanding story amazing", "fantastic film excellent", "brilliant movie great",
    "incredible acting perfect", "superb story wonderful", "great film amazing",
    "excellent acting fantastic", "wonderful film brilliant", "amazing movie incredible",
    "perfect story superb"] * 2

In [18]:
negative_reviews = [
    "terrible movie awful", "horrible film bad", "poor story terrible",
    "awful acting horrible", "worst movie terrible", "bad film poor",
    "horrible story awful", "terrible acting bad", "poor movie worst",
    "awful film horrible", "bad story terrible", "poor acting awful",
    "terrible film horrible", "worst story bad", "horrible movie poor",
    "awful story terrible", "bad film horrible", "poor movie awful",
    "terrible acting worst", "horrible story bad", "awful movie poor",
    "bad acting terrible", "poor film horrible", "terrible story awful",
    "horrible acting bad"
] * 2

In [20]:
all_reviews = positive_reviews + negative_reviews # combine reviews
all_sentiments = ['positive']* 50 + ['negative']* 50

In [21]:
df_reviews = pd.DataFrame({
    'review': all_reviews,
    'sentiment': all_sentiments
})

In [22]:
print(df_reviews.head(10))

                       review sentiment
0        great movie loved it  positive
1      amazing film wonderful  positive
2   excellent story fantastic  positive
3     brilliant acting superb  positive
4       perfect movie amazing  positive
5      outstanding film great  positive
6   wonderful story excellent  positive
7  fantastic acting brilliant  positive
8    incredible movie perfect  positive
9     superb film outstanding  positive


In [23]:
#  Tokenize the reviews using CountVectorizer with a maximum of 500 features,
# removing stop words

In [43]:
vectorizer =  CountVectorizer(max_features= 500, stop_words='english')
X = vectorizer.fit_transform(df_reviews['review'])
y = df_reviews['sentiment']

In [44]:
print(f"Converted {len(df_reviews)} reviews into {X.shape[1]} features")

Converted 100 reviews into 21 features


In [45]:
# split data into trainign and testing

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"training samples: {X_train.shape[0]}")
print(f"testing samples: {X_test.shape[0]}")

training samples: 80
testing samples: 20


In [47]:
# train naive bayes model

In [48]:
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

MultinomialNB()

In [49]:
# test NB

In [50]:
y_pred = nb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"model accuracy: {accuracy:.1%}")

model accuracy: 100.0%


In [51]:
#function predict_review_sentiment(model, vectorizer, review)

In [54]:
def predict_review_sentiment(model, vectorizer, review):
    
    review_numbers = vectorizer.transform([review]) # convert reviews to no.s
    
    prediction = model.predict(review_numbers)[0]
    print(f" prediction: {prediction}")
    
    return prediction

In [55]:
# test with new review
test_review = "this movie was fantastic and amazing"
predicted_sentiment = predict_review_sentiment(nb_model, vectorizer, test_review)

 prediction: positive


## problem 5

In [56]:
# product feedback

In [57]:
good_base = [
    "great product excellent quality", "amazing service fast delivery", 
    "perfect item works well", "outstanding quality good value",
    "excellent product fast shipping", "great experience good support",
    "amazing quality perfect item", "outstanding service excellent product",
    "perfect quality great value", "excellent service amazing product"
]

In [60]:
bad_base = [
    "poor product terrible quality", "awful service slow delivery",
    "defective item broken product", "poor quality bad value", 
    "terrible product slow shipping", "bad experience poor support",
    "awful quality defective item", "poor service terrible product",
    "defective quality poor value", "terrible service awful product"
]

In [62]:
good_feedback = []
bad_feedback = []

for i in range(50):
    good_feedback.append(good_base[i % len(good_base)])
    bad_feedback.append(bad_base[i % len(bad_base)])

In [64]:
all_feedback = good_feedback + bad_feedback
all_labels = ['good']* 50 + ['bad']* 50



df_feedback = pd.DataFrame({
    'feedback': all_feedback,
    'label': all_labels
})

print(df_feedback.head(10))

                                feedback label
0        great product excellent quality  good
1          amazing service fast delivery  good
2                perfect item works well  good
3         outstanding quality good value  good
4        excellent product fast shipping  good
5          great experience good support  good
6           amazing quality perfect item  good
7  outstanding service excellent product  good
8            perfect quality great value  good
9      excellent service amazing product  good


In [66]:
tfidf_vectorizer = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X_tfidf = tfidf_vectorizer.fit_transform(df_feedback['feedback'])
y_labels = df_feedback['label']


print(f"converted {len(df_feedback)} feedback samples into {X_tfidf.shape[1]} features")

converted 100 feedback samples into 24 features


In [67]:
# splitting data

In [68]:
X_train_tfidf, X_test_tfidf, y_train_labels, y_test_labels = train_test_split(
    X_tfidf, y_labels, test_size=0.25, random_state=42
)
print(f"Training samples: {X_train_tfidf.shape[0]}")  
print(f"Testing samples: {X_test_tfidf.shape[0]}")   

Training samples: 75
Testing samples: 25


In [69]:
# logistic regression

In [70]:
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train_tfidf, y_train_labels)

# test model
y_pred_labels = lr_model.predict(X_test_tfidf)

In [71]:
precision = precision_score(y_test_labels, y_pred_labels, pos_label='good')
recall = recall_score(y_test_labels, y_pred_labels, pos_label='good')
f1 = f1_score(y_test_labels, y_pred_labels, pos_label='good')

In [72]:
print(f"precision: {precision:.3f}")
print(f"recall: {recall:.3f}")
print(f"f1 score: {f1:.3f} ")

precision: 1.000
recall: 1.000
f1 score: 1.000 


In [77]:
# function text_preprocess_vectorize(texts, vectorizer) 

In [79]:
def text_preprocess_vectorize(texts, vectorizer):
    
    feature_matrix = vectorizer.transform(texts)
    
    print(f"created matrix with shape: {feature_matrix.shape}")
    return feature_matrix

In [80]:
# test
test_texts = ["great product amazing quality", "terrible item poor service"]
feature_matrix = text_preprocess_vectorize(test_texts, tfidf_vectorizer)

created matrix with shape: (2, 24)


In [81]:
# tst predictions on new texts
test_predictions = lr_model.predict(feature_matrix)
print("Test predictions:")
for i, text in enumerate(test_texts):
    print(f"'{text}' -> {test_predictions[i]}")

Test predictions:
'great product amazing quality' -> good
'terrible item poor service' -> bad
